# Generated by Django 3.0.2 on 2021-01-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='idcard',
            field=models.ImageField(default='default.jpg', upload_to='first'),
        ),
    ]
