# Generated by Django 3.0.2 on 2021-01-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210121_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='idcard',
            field=models.ImageField(default='default.jpg', upload_to='idcard'),
        ),
    ]
