# Generated by Django 3.0.2 on 2021-01-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210121_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idnumber',
            field=models.CharField(default='', max_length=50),
        ),
    ]
