# Generated by Django 2.2.13 on 2021-03-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_idnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.CharField(choices=[('Attendee', 'Attendee'), ('Organizer', 'Organizer')], default='Attendee', max_length=10),
        ),
    ]
