# Generated by Django 2.2.13 on 2021-03-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210313_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.CharField(blank=True, choices=[('Attendee', 'Attendee'), ('Organizer', 'Organizer')], default='Attendee', max_length=10, null=True),
        ),
    ]
