# Generated by Django 2.2.13 on 2021-03-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210313_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.CharField(choices=[('Attendee', 'Attendee'), ('Organizer', 'Organizer')], default='Attendee', max_length=10, null=True),
        ),
    ]
