# Generated by Django 2.2.13 on 2021-03-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210313_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numberofupdates',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
