# Generated by Django 3.0.2 on 2021-01-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(null=True)),
                ('organizer', models.CharField(max_length=100)),
                ('joiningfees', models.CharField(max_length=10)),
                ('pricemoney', models.CharField(max_length=10)),
                ('members', models.CharField(max_length=5, null=True)),
                ('link', models.CharField(max_length=100)),
                ('Eventtime', models.CharField(max_length=20)),
                ('venue', models.TextField()),
            ],
        ),
    ]
