# Generated by Django 3.0.2 on 2021-01-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='Category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='EventDate',
            field=models.DateField(null=True),
        ),
    ]
