# Generated by Django 3.0.2 on 2021-01-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210121_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlist',
            name='EventDate',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='date',
        ),
        migrations.AddField(
            model_name='eventlist',
            name='Endingdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='StartingDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='numberofseats',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
