# Generated by Django 2.2.13 on 2021-01-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventlist_postby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='Endingdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='StartingDate',
            field=models.DateTimeField(null=True),
        ),
    ]
