# Generated by Django 2.2.13 on 2021-01-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210125_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('eventid', models.CharField(max_length=100)),
                ('booking', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
    ]
