# Generated by Django 2.2.13 on 2021-01-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbook',
            name='booking_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
