# Generated by Django 2.2.13 on 2021-02-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_eventbook_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbook',
            name='certificate',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='certificates'),
        ),
    ]
