# Generated by Django 2.2.13 on 2021-02-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20210203_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbook',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates'),
        ),
    ]
