# Generated by Django 2.2.13 on 2021-02-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20210203_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbook',
            name='certificate',
            field=models.ImageField(blank=True, default='coming_soon.jpg', null=True, upload_to='certificates'),
        ),
    ]
