# Generated by Django 2.2.13 on 2021-03-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20210226_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='thumbnail',
            field=models.ImageField(blank=True, default='event.jpg', null=True, upload_to='events_thumbnail'),
        ),
    ]
